"Dataset cleaned — handled NaN values in Fat and Sat.Fat with fillna(0), dropped rows with missing Calories/Protein/Fiber/Carbs. 335 rows → 291 rows."

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\DEVIL\PythonPrograms\nutrients_csvfile.csv")
print(df.shape)
print(df.head())

(335, 10)
                    Food Measure  Grams Calories Protein Fat Sat.Fat Fiber  \
0             Cows' milk   1 qt.    976      660      32  40      36     0
1              Milk skim   1 qt.    984      360      36   t       t     0
2             Buttermilk   1 cup    246      127       9   5       4     0
3  Evaporated, undiluted   1 cup    252      345      16  20      18     0
4         Fortified milk  6 cups  1,419    1,373      89  42      23   1.4

  Carbs        Category
0    48  Dairy products
1    52  Dairy products
2    13  Dairy products
3    24  Dairy products
4   119  Dairy products

In [2]:
print(df.shape)

(335, 10)

In [3]:
print(df["Category"].unique())

['Dairy products' 'Fats, Oils, Shortenings' 'Meat, Poultry'
 'Fish, Seafood' 'Vegetables A-E' 'Vegetables F-P' 'Vegetables R-Z'
 'Fruits A-F' 'Fruits G-P' 'Fruits R-Z' 'Breads, cereals, fastfood,grains'
 'Soups' 'Desserts, sweets' 'Jams, Jellies' 'Seeds and Nuts'
 'Drinks,Alcohol, Beverages']

In [4]:
print(df.describe())

          Food Measure Grams Calories Protein  Fat Sat.Fat Fiber Carbs  \
count      335     335   335      334     335  335     333   335   335
unique     329      61   103      152      40   45      38    57    80
top     Butter   1 cup   100      100       1    t       0     0     0
freq         3     120    38       14      53  115     174   116    45

                                Category
count                                335
unique                                16
top     Breads, cereals, fastfood,grains
freq                                  45

In [5]:
dairy = df[df["Category"] == "Dairy products"]
print(dairy)

                       Food     Measure  Grams Calories Protein Fat Sat.Fat  \
0                Cows' milk       1 qt.    976      660      32  40      36
1                 Milk skim       1 qt.    984      360      36   t       t
2                Buttermilk       1 cup    246      127       9   5       4
3     Evaporated, undiluted       1 cup    252      345      16  20      18
4            Fortified milk      6 cups  1,419    1,373      89  42      23
5             Powdered milk       1 cup    103      515      27  28      24
6             skim, instant  1 1/3 cups     85      290      30   t       t
7         skim, non-instant     2/3 cup     85      290      30   t       t
8               Goats' milk       1 cup    244      165       8  10       8
9       (1/2 cup ice cream)      2 cups    540      690      24  24      22
10                    Cocoa       1 cup    252      235       8  11      10
11               skim. milk       1 cup    250      128      18   4       3
12             (cornstarch)       1 cup    248      275       9  10       9
13                  Custard       1 cup    248      285      13  14      11
14                Ice cream       1 cup    188      300       6  18      16
15                 Ice milk       1 cup    190      275       9  10       9
16   Cream or half-and-half     1/2 cup    120      170       4  15      13
17              or whipping     1/2 cup    119      430       2  44      27
18                   Cheese       1 cup    225      240      30  11      10
19                uncreamed       1 cup    225      195      38   t       t
20                  Cheddar  1-in. cube     17       70       4   6       5
21      Cheddar, grated cup     1/2 cup     56      226      14  19      17
22             Cream cheese       1 oz.     28      105       2  11      10
23         Processed cheese       1 oz.     28      105       7   9       8
24           Roquefort type       1 oz.     28      105       6   9       8
25                    Swiss       1 oz.     28      105       7   8       7
26                 Eggs raw           2    100      150      12  12      10
27  Eggs Scrambled or fried           2    128      220      13  16      14

   Fiber Carbs        Category
0      0    48  Dairy products
1      0    52  Dairy products
2      0    13  Dairy products
3      0    24  Dairy products
4    1.4   119  Dairy products
5      0    39  Dairy products
6      0    42  Dairy products
7      1    42  Dairy products
8      0    11  Dairy products
9      0    70  Dairy products
10     0    26  Dairy products
11     1    13  Dairy products
12     0    40  Dairy products
13     0    28  Dairy products
14     0    29  Dairy products
15     0    32  Dairy products
16     0     5  Dairy products
17     1     3  Dairy products
18     0     6  Dairy products
19     0     6  Dairy products
20     0     t  Dairy products
21     0     1  Dairy products
22     0     1  Dairy products
23     0     t  Dairy products
24     0     t  Dairy products
25     0     t  Dairy products
26     0     t  Dairy products
27     0     1  Dairy products

In [6]:
meat = df[df["Category"] == "Meat, Poultry"]
print(meat.shape)

(30, 10)

In [7]:
fish = df[df["Category"] == "Fish, Seafood"]
print(fish.shape)

(19, 10)

In [8]:
print(df["Category"].value_counts())

Category
Breads, cereals, fastfood,grains    45
Meat, Poultry                       30
Desserts, sweets                    29
Dairy products                      28
Vegetables A-E                      28
Vegetables R-Z                      28
Fruits G-P                          28
Fruits A-F                          22
Fish, Seafood                       19
Fats, Oils, Shortenings             14
Vegetables F-P                      14
Seeds and Nuts                      12
Drinks,Alcohol, Beverages           12
Soups                               10
Fruits R-Z                           8
Jams, Jellies                        8
Name: count, dtype: int64

In [9]:
fish = df[df["Category"] == "Fish, Seafood"][["Food", "Calories", "Protein"]]
print(fish)

                 Food Calories Protein
72              Clams       87      12
73                Cod      170      28
74          Crab meat       90      14
75  Fish sticks fried      200      19
76           Flounder      200      30
77            Haddock      135      16
78            Halibut      182      26
79            Herring      211      22
80            Lobster       92      18
81           Mackerel      155      18
82            Oysters      231     232
83        Oyster stew      125      19
84             Salmon      120      17
85           Sardines      180      22
86           Scallops      104      18
87               Shad      170      20
88             Shrimp      110      23
89          Swordfish      180      27
90               Tuna      170      25

In [10]:
df.loc[82, ["Calories", "Protein", "Fat", "Sat.Fat", "Fiber", "Carbs"]] = [150, 18, 5, 1, 0, 9]
print(df.loc[82])

Food              Oysters
Measure          6-8 med.
Grams                 230
Calories              150
Protein                18
Fat                     5
Sat.Fat                 1
Fiber                   0
Carbs                   9
Category    Fish, Seafood
Name: 82, dtype: object

In [11]:
suspicious = df[df["Protein"] > df["Calories"]]
print(suspicious)

                      Food     Measure  Grams Calories Protein Fat Sat.Fat  \
2               Buttermilk       1 cup    246      127       9   5       4
4           Fortified milk      6 cups  1,419    1,373      89  42      23
6            skim, instant  1 1/3 cups     85      290      30   t       t
7        skim, non-instant     2/3 cup     85      290      30   t       t
8              Goats' milk       1 cup    244      165       8  10       8
..                     ...         ...    ...      ...     ...  ..     ...
322                Walnuts     1/2 cup     50      325       7  32       7
323                   Beer      2 cups    480      228       t   0       0
325                  Wines     1/2 cup    120      164       t   0       0
326  Table (12.2% alcohol)     1/2 cup    120      100       t   0       0
333                 Coffee       1 cup    230        3       t   0       0

    Fiber Carbs                   Category
2       0    13             Dairy products
4     1.4   119             Dairy products
6       0    42             Dairy products
7       1    42             Dairy products
8       0    11             Dairy products
..    ...   ...                        ...
322     1     8             Seeds and Nuts
323     0     8  Drinks,Alcohol, Beverages
325     0     9  Drinks,Alcohol, Beverages
326     0     5  Drinks,Alcohol, Beverages
333     0     1  Drinks,Alcohol, Beverages

[150 rows x 10 columns]

In [12]:
df["Calories"] = pd.to_numeric(df["Calories"], errors = "coerce")
df["Protein"] = pd.to_numeric(df["Calories"], errors = "coerce")
df["Fat"] = pd.to_numeric(df["Fat"], errors = "coerce")
df["Sat.Fat"] = pd.to_numeric(df["Sat.Fat"], errors = "coerce")
df["Fiber"] = pd.to_numeric(df["Fiber"], errors = "coerce")
df["Carbs"] = pd.to_numeric(df["Carbs"], errors="coerce")

suspicious = df[df["Protein"] > df["Calories"]]
print(suspicious[["Food", "Calories", "Protein"]])
print("Total suspicious rows:", len(suspicious))

Empty DataFrame
Columns: [Food, Calories, Protein]
Index: []
Total suspicious rows: 0

In [13]:
df.isnull().sum()

Food          0
Measure       0
Grams         0
Calories      5
Protein       5
Fat         116
Sat.Fat      17
Fiber        27
Carbs        13
Category      0
dtype: int64

In [14]:
df[df["Fat"].isnull()].head(10)

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category
1,Milk skim,1 qt.,984,360.0,360.0,NaN,NaN,0.0,52.0,Dairy products
6,"skim, instant",1 1/3 cups,85,290.0,290.0,NaN,NaN,0.0,42.0,Dairy products
7,"skim, non-instant",2/3 cup,85,290.0,290.0,NaN,NaN,1.0,42.0,Dairy products
19,uncreamed,1 cup,225,195.0,195.0,NaN,NaN,0.0,6.0,Dairy products
91,Artichoke,1 large,100,NaN,NaN,NaN,NaN,2.0,10.0,Vegetables A-E
92,Asparagus,6 spears,96,18.0,18.0,NaN,NaN,0.5,3.0,Vegetables A-E
93,Beans,1 cup,125,25.0,25.0,NaN,NaN,0.8,6.0,Vegetables A-E
94,Lima,1 cup,160,140.0,140.0,NaN,NaN,3.0,24.0,Vegetables A-E
95,"Lima, dry, cooked",1 cup,192,260.0,260.0,NaN,NaN,2.0,48.0,Vegetables A-E
98,Bean sprouts,1 cup,50,17.0,17.0,NaN,0.0,0.3,3.0,Vegetables A-E

In [15]:
df["Fat"] = df["Fat"].fillna(0)

In [16]:
df["Sat.Fat"] = df["Sat.Fat"].fillna(0)
df.dropna(inplace = True)
df.isnull().sum()

Food        0
Measure     0
Grams       0
Calories    0
Protein     0
Fat         0
Sat.Fat     0
Fiber       0
Carbs       0
Category    0
dtype: int64

In [17]:
len(df)

291

In [18]:
df.groupby("Category")["Calories"].mean().sort_values(ascending=False)

Category
Seeds and Nuts                      340.750000
Dairy products                      296.636364
Meat, Poultry                       267.185185
Fats, Oils, Shortenings             265.888889
Breads, cereals, fastfood,grains    240.171429
Desserts, sweets                    238.120000
Jams, Jellies                       184.285714
Fruits R-Z                          153.500000
Fish, Seafood                       152.000000
Fruits A-F                          151.272727
Fruits G-P                          126.208333
Soups                               119.100000
Vegetables R-Z                      106.625000
Drinks,Alcohol, Beverages            94.727273
Vegetables A-E                       68.384615
Vegetables F-P                       58.083333
Name: Calories, dtype: float64

In [19]:
df.groupby("Category")["Protein"].mean().sort_values(ascending=False)

Category
Seeds and Nuts                      340.750000
Dairy products                      296.636364
Meat, Poultry                       267.185185
Fats, Oils, Shortenings             265.888889
Breads, cereals, fastfood,grains    240.171429
Desserts, sweets                    238.120000
Jams, Jellies                       184.285714
Fruits R-Z                          153.500000
Fish, Seafood                       152.000000
Fruits A-F                          151.272727
Fruits G-P                          126.208333
Soups                               119.100000
Vegetables R-Z                      106.625000
Drinks,Alcohol, Beverages            94.727273
Vegetables A-E                       68.384615
Vegetables F-P                       58.083333
Name: Protein, dtype: float64

In [20]:
df[["Food", "Calories", "Protein"]].head(10)

                     Food  Calories  Protein
0              Cows' milk     660.0    660.0
1               Milk skim     360.0    360.0
2              Buttermilk     127.0    127.0
3   Evaporated, undiluted     345.0    345.0
5           Powdered milk     515.0    515.0
6           skim, instant     290.0    290.0
7       skim, non-instant     290.0    290.0
8             Goats' milk     165.0    165.0
9     (1/2 cup ice cream)     690.0    690.0
10                  Cocoa     235.0    235.0

In [21]:
df = pd.read_csv(r"C:\Users\DEVIL\PythonPrograms\nutrients_csvfile.csv")
df["Calories"] = pd.to_numeric(df["Calories"], errors = "coerce")
df["Protein"] = pd.to_numeric(df["Protein"], errors = "coerce")
df["Fat"] = pd.to_numeric(df["Fat"], errors = "coerce")
df["Sat.Fat"] = pd.to_numeric(df["Sat.Fat"], errors = "coerce")
df["Fiber"] = pd.to_numeric(df["Fiber"], errors = "coerce")
df["Carbs"] = pd.to_numeric(df["Carbs"], errors = "coerce")
df["Fat"] = df["Fat"].fillna(0)
df["Sat.Fat"] = df["Sat.Fat"].fillna(0)
df.dropna(inplace=True)
df[["Food", "Calories", "Protein"]].head(10)

                     Food  Calories  Protein
0              Cows' milk     660.0     32.0
1               Milk skim     360.0     36.0
2              Buttermilk     127.0      9.0
3   Evaporated, undiluted     345.0     16.0
5           Powdered milk     515.0     27.0
6           skim, instant     290.0     30.0
7       skim, non-instant     290.0     30.0
8             Goats' milk     165.0      8.0
9     (1/2 cup ice cream)     690.0     24.0
10                  Cocoa     235.0      8.0

In [22]:
df.groupby("Category")["Protein"].mean().sort_values(ascending=False)

Category
Fish, Seafood                       33.529412
Fats, Oils, Shortenings             32.571429
Meat, Poultry                       18.666667
Dairy products                      17.181818
Seeds and Nuts                      10.000000
Breads, cereals, fastfood,grains     7.942857
Soups                                5.900000
Vegetables R-Z                       4.409091
Vegetables A-E                       4.125000
Vegetables F-P                       3.800000
Desserts, sweets                     3.350000
Fruits A-F                           1.705882
Fruits R-Z                           1.400000
Fruits G-P                           1.227273
Drinks,Alcohol, Beverages            0.000000
Jams, Jellies                        0.000000
Name: Protein, dtype: float64

In [23]:
df.groupby("Category")["Fat"].mean().sort_values(ascending=False)

Category
Fats, Oils, Shortenings             68.857143
Seeds and Nuts                      30.666667
Fish, Seafood                       19.823529
Meat, Poultry                       19.592593
Dairy products                      14.090909
Desserts, sweets                     6.100000
Soups                                4.100000
Breads, cereals, fastfood,grains     3.828571
Vegetables R-Z                       3.136364
Fruits A-F                           1.176471
Fruits G-P                           1.136364
Vegetables A-E                       0.375000
Fruits R-Z                           0.200000
Vegetables F-P                       0.200000
Drinks,Alcohol, Beverages            0.000000
Jams, Jellies                        0.000000
Name: Fat, dtype: float64

In [24]:
df.columns

Index(['Food', 'Measure', 'Grams', 'Calories', 'Protein', 'Fat', 'Sat.Fat',
       'Fiber', 'Carbs', 'Category'],
      dtype='object')

In [25]:
df["protein_per_calorie"] = df["Protein"] / df["Calories"]
print(df[["Food", "Calories", "Protein", "protein_per_calorie"]])

                      Food  Calories  Protein  protein_per_calorie
0               Cows' milk     660.0     32.0             0.048485
1                Milk skim     360.0     36.0             0.100000
2               Buttermilk     127.0      9.0             0.070866
3    Evaporated, undiluted     345.0     16.0             0.046377
5            Powdered milk     515.0     27.0             0.052427
..                     ...       ...      ...                  ...
329            Cola drinks     137.0      0.0             0.000000
330    Fruit-flavored soda     161.0      0.0             0.000000
331             Ginger ale     105.0      0.0             0.000000
332              Root beer     140.0      0.0             0.000000
334                    Tea       4.0      0.0             0.000000

[263 rows x 4 columns]

In [26]:
print(df.sort_values("protein_per_calorie", ascending=False)[["Food", "Calories", "Protein", "protein_per_calorie"]].head(10))

                       Food  Calories  Protein  protein_per_calorie
31                   Butter     113.0    114.0             1.008850
30                   Butter     113.0    114.0             1.008850
82                  Oysters     231.0    232.0             1.004329
88                   Shrimp     110.0     23.0             0.209091
266                Bouillon      24.0      5.0             0.208333
110               Stalk raw       5.0      1.0             0.200000
19                uncreamed     195.0     38.0             0.194872
86                 Scallops     104.0     18.0             0.173077
52   Corned beef hash Dried     115.0     19.0             0.165217
73                      Cod     170.0     28.0             0.164706

In [34]:
df[df["Food"].str.contains("Butter | Oysters", case=False)]

Empty DataFrame
Columns: [Food, Measure, Grams, Calories, Protein, Fat, Sat.Fat, Fiber, Carbs, Category, protein_per_calorie]
Index: []

In [36]:
df.loc[[30, 31, 82]]

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category,protein_per_calorie
30,Butter,1/2 cup,112,113.0,114.0,115.0,116.0,117.0,118.0,"Fats, Oils, Shortenings",1.008850
31,Butter,1/4 lb.,112,113.0,114.0,115.0,116.0,117.0,118.0,"Fats, Oils, Shortenings",1.008850
82,Oysters,6-8 med.,230,231.0,232.0,233.0,234.0,235.0,236.0,"Fish, Seafood",1.004329

In [37]:
df = df.drop([30, 31, 82])
print(len(df))

260

In [38]:
print(df.sort_values("protein_per_calorie", ascending=False)[["Food", "Calories", "Protein", "protein_per_calorie"]].head(10))

                       Food  Calories  Protein  protein_per_calorie
88                   Shrimp     110.0     23.0             0.209091
266                Bouillon      24.0      5.0             0.208333
110               Stalk raw       5.0      1.0             0.200000
19                uncreamed     195.0     38.0             0.194872
86                 Scallops     104.0     18.0             0.173077
52   Corned beef hash Dried     115.0     19.0             0.165217
73                      Cod     170.0     28.0             0.164706
58    Chicken livers, fried     140.0     22.0             0.157143
74                Crab meat      90.0     14.0             0.155556
83              Oyster stew     125.0     19.0             0.152000

    "Top 10 foods by protein efficiency — seafood dominates. Confirmed by both individual ranking and category-level GroupBy analysis."